### PR TITLE
Masks for zero-width fields of mems should be width zero.

### LINKED ISSUE #666: Mems with 0-width entries can't be assigned to
The following firrtl crashes the compiler:
```
circuit BadMem :
  module BadMem :
    input clk  : Clock
    input addr : UInt<4>
    input in   : {0: UInt<10>, 1: UInt<0>}

    cmem ram : {0: UInt<10>, 1: UInt<0>}[16]
    infer mport ramin = ram[addr], clk

    ramin.0 <= in.0
    ramin.1 <= in.1
```

I get the error `java.util.NoSuchElementException: key not found: ram_1`. I think this should be legal firrtl.

FWIW, if you switch in to an output and flip the assignments, everything works fine.

### PR DESCRIPTION
**Pull request by grebe**
Closes #666.

### CODE REVIEW

File: src/main/scala/firrtl/passes/memlib/MemUtils.scala [hunk 1]
```diff
@@ -46,6 +46,7 @@ object createMask {
   def apply(dt: Type): Type = dt match {
     case t: VectorType => VectorType(apply(t.tpe), t.size)
     case t: BundleType => BundleType(t.fields map (f => f copy (tpe=apply(f.tpe))))
+    case GroundType(w) if w == IntWidth(0) => UIntType(IntWidth(0))
```
Comment (grebe) [inline src/main/scala/firrtl/passes/memlib/MemUtils.scala]: Is there a nicer syntax for this?

Comment (chick) [reply src/main/scala/firrtl/passes/memlib/MemUtils.scala]: How about
```case GroundType(IntWidth(0)) => UIntType(IntWidth(0))```
?

Comment (grebe) [reply src/main/scala/firrtl/passes/memlib/MemUtils.scala]: You'd think so, but the unapply for intwidth wants a BigInt, and `GroundType(IntWidth(BigInt(0)))` gave me some other weird error that I didn't really understand (maybe `BigInt` has its own unapply doing something weird?).

Comment (azidar) [reply src/main/scala/firrtl/passes/memlib/MemUtils.scala]: Yeah, it doesn't work. What you can do is somewhere define:
```val zeroW = IntWidth(0)```
and then you can do:
```case GroundType(`zeroW`) => ...```

**Comment by azidar** [comment]
Either merge it when you are ready, or if you don't have write access, ping me and I'll do it.

File: src/main/scala/firrtl/passes/memlib/MemUtils.scala (hunk 1 above)
Comment (grebe) [reply src/main/scala/firrtl/passes/memlib/MemUtils.scala]: Ah, good point- I rarely use the backticks, but this is a good example where it would be good. I think it's a wash and I'll just leave the existing syntax. Thanks!
