### PR TITLE
Fix verilog prep

### LINKED ISSUE #1931: Rename error in VerilogPrep.
### Checklist

- [x] Did you specify the current behavior?
- [x] Did you specify the expected behavior?
- [x] Did you provide a code example showing the problem?
- [x] Did you describe your environment?
- [x] Did you specify relevant external information?

### What is the current behavior?
`VerilogPrep|run|lowerS` match and use `tpe` in `WDefInstance(info, name, module, tpe)`. 
But when this type is `BundleType`, it contains `firrtl.ir.Field`, not recorded in `firrtl.transforms.ManipulateNames`.
This causes: when `VerilogPrep` use it to construct `WDefInstanceConnector`, signal can be renamed, while `BundleType.field` cannot. port name will be wrong
.
Here is the simple demo: https://scastie.scala-lang.org/rJXAOXDOTlqv1CbhDMBE4A
```
Inverter inv ( // @[main.scala 15:19]
    .input(inv_input),
    .output(inv_output)
  );
```
should be
```
Inverter inv ( // @[main.scala 15:19]
    .input_(inv_input),
    .output_(inv_output)
  );
```

### What is the expected behavior?
Verilog should be generated correctly.
`Field` of `BundleType` should be renamed.

### Your environment
- Chisel Verions: 3.4.0

### PR DESCRIPTION
**Pull request by sequencer**
### Contributor Checklist

<del>- [ ] Did you add Scaladoc to every public function/method?</del>
<del>- [ ] Did you update the FIRRTL spec to include every new feature/behavior?</del>
- [x] Did you add at least one test demonstrating the PR?
- [x] Did you delete any extraneous printlns/debugging code?
- [x] Did you specify the type of improvement?
- [x] Did you state the API impact?
- [x] Did you specify the code generation impact?
- [x] Did you request a desired merge strategy?
- [x] Did you add text to be included in the Release Notes for this change?

#### Type of Improvement
- bug fix

#### API Impact
None

#### Backend Code Generation Impact
Fix #1931 

#### Desired Merge Strategy
- Rebase: You will rebase the PR onto master and it will be merged with a merge commit.

#### Release Notes
Bug fix for rename error in VerilogPrep.

### Reviewer Checklist (only modified by reviewer)
- [ ] Did you add the appropriate labels?
- [ ] Did you mark the proper milestone (1.2.x, 1.3.0, 1.4.0) ?
- [ ] Did you review?
- [ ] Did you check whether all relevant Contributor checkboxes have been checked?
- [ ] Did you mark as `Please Merge`?

### CODE REVIEW

File: src/test/scala/firrtlTests/VerilogEmitterTests.scala [hunk 1]
```diff
@@ -441,32 +442,46 @@ class VerilogEmitterSpec extends FirrtlFlatSpec {
...
+        |endmodule
+        |module endmodule_(
+        |  output  fork_
+        |);
+        |  wire [4:0] const_ = 5'h2;
+        |  assign fork_ = 1'h0;
+        |endmodule
+        |""".stripMargin.split('\n')
+    val circuit = parse(input)
+    val annotations = (new FirrtlStage).run(Seq(
```
Comment (seldridge) [inline src/test/scala/firrtlTests/VerilogEmitterTests.scala:477]:
```suggestion
    val annotations = (new FirrtlStage).transform(Seq(
```

This was made protected, but should work with `transform`.

**Review by seldridge — APPROVED** [review]
Switching to examining the actual Verilog output makes sense to me.

Thanks for fixing this!

File: src/test/scala/firrtlTests/VerilogEmitterTests.scala (hunk 1 above)
Comment (sequencer) [reply src/test/scala/firrtlTests/VerilogEmitterTests.scala]: Sorry for this bug. It should be resolved now.

Comment (seldridge) [reply src/test/scala/firrtlTests/VerilogEmitterTests.scala]: No need to apologize! This was a crappy API design on my part with `run`... Thanks for the quick fix.
