### PR TITLE
InferWidths: improve performance

### LINKED ISSUE #842: InferWidths is pathologically slow on a 138 KB circuit
**Type of issue**: bug report (performance)

A 138 KB circuit is taking 64 minutes to run through FIRRTL to generate Verilog from Chirrtl.

Profiling indicates that InferWidths is taking most of the time, with `InferWidths.collectMinMax` taking most of the time.

Chisel3 takes <1 minute to elaborate to FIRRTL, and before this RTL was ported to Chisel3, Chisel2 was able to elaborate to Verilog in <1 minute, so this is a serious performance regression from a user's perspective.

Reproduced on firrtl master (revision ceac36d), locally and on a-machines.

[FIRRTL file](https://gist.github.com/edwardcwang/b13bd38d4b5aea5b879861a16c57649e) (138 KB)

---
`firrtl -i Core-test.fir -o Core-test-out -X verilog` - `Total FIRRTL Compile Time: 6766360.7 ms` (112.8 min)
`firrtl -i Core-test.fir -o Core-test-out -X verilog --no-check-comb-loops --no-dce` - `Total FIRRTL Compile Time: 880962.3 ms` (14.7 min)

### PR DESCRIPTION
**Pull request by edwardcwang**
On circuits with large numbers of width inferences, prepend to a linked list instead of appending and having to make a copy.

Thanks @azidar for the catch

Close #842

### CODE REVIEW

File: src/main/scala/firrtl/passes/InferWidths.scala [hunk 1]
```diff
@@ -42,12 +42,12 @@ object InferWidths extends Pass {
     }
     def collectMinMax(w: Width): Width = w map collectMinMax match {
       case MinWidth(args) => MinWidth(unique((args.foldLeft(Seq[Width]())) {
```
Comment (jackkoenig) [inline src/main/scala/firrtl/passes/InferWidths.scala]: All over the place we tend to use `Seq(...)` and `Seq.empty` to create sequences when I think we should be a more explicit and call out what data structure we're instantiating. Since the appending was causing such massive problems, can you also change it to `List[Width]()` (which is what `Seq[Width]()` creates) just to be a little more obvious?

Comment (edwardcwang) [reply src/main/scala/firrtl/passes/InferWidths.scala]: Done. Interesting comparison of `List` vs `Vector`: https://docs.scala-lang.org/overviews/collections/performance-characteristics.html

File: src/main/scala/firrtl/passes/InferWidths.scala [hunk 2]
```diff
@@ -41,13 +41,13 @@ object InferWidths extends Pass {
       case wx => wx
     }
     def collectMinMax(w: Width): Width = w map collectMinMax match {
-      case MinWidth(args) => MinWidth(unique((args.foldLeft(Seq[Width]())) {
-        case (res, wxx: MinWidth) => res ++ wxx.args
-        case (res, wxx) => res :+ wxx
+      case MinWidth(args) => MinWidth(unique((args.foldLeft(List[Width]())) {
+        case (res, wxx: MinWidth) => wxx.args.toList ++ res
```
Comment (jackkoenig) [inline src/main/scala/firrtl/passes/InferWidths.scala]: I'm actually not certain if this matters in practice (eg. compile *may* do the right thing automatically, but you could do `wxx.args ++: res` so that the append operator returns the type of the right collection rather than the left collection like `++` does. This potentially saves a traversal and construction of a List from the args of `wxx`

Comment (edwardcwang) [reply src/main/scala/firrtl/passes/InferWidths.scala]: Done.

File: src/main/scala/firrtl/passes/InferWidths.scala (hunk 1 above)
Comment (jackkoenig) [reply src/main/scala/firrtl/passes/InferWidths.scala]: See also http://www.lihaoyi.com/post/BenchmarkingScalaCollections.html
