### PR TITLE
Better error message on missing BlackBox resource

### LINKED ISSUE #893: FIR crashes when incorrect Verilog resource is provided for a BlackBox
FIR violently crashes with the msg below when an invalid resource Verilog file is provided in a Black Box instantiation:
[error] (run-main-15) firrtl.FIRRTLException: Internal Error! Please file an issue at https://github.com/ucb-bar/firrtl/issues

```scala
class VxuIO () extends Bundle {
  // stuff
}

class Vxu extends Module {
  val io  = IO(new VxuIO)
  val vxu = Module (new VxuImpl)
  vxu.io <> io  
}

class VxuImpl extends BlackBox with HasBlackBoxResource {
  val io  = IO(new VxuIO)
  setResource ("/VxuImpl0.v")
}

```
Of course, VxuImp.v is present in /src/main/resources and this code works with correct Verilog name

### PR DESCRIPTION
**Pull request by seldridge**
Fixes #893 

If you try to access a non-existent BlackBox resource, this should generate a `FIRRTLException` child and not a raw `FileNotFoundException`. The latter will cause the "internal FIRRTL error, file an issue" message while the former does not. 

This fixes this for both `BlackBoxPathAnno` and `BlackBoxResourceAnno` by wrapping calls that interact with the (possibly non-existent) resource file in a method that will rethrow `FileNotFoundException` as a new `BlackBoxNotFoundException extends FIRRTLException`. 

Small changes:
  - The manually thrown `FileNotFoundException` by `BlackBoxSourceHelper.copyResourceToFile` is changed to match what other java methods will do (e.g., `FileInputStream.getChannel`)

Example output looks like:
```
[info] - should provide a useful error message for BlackBoxResourceAnno *** FAILED ***
[info]   firrtl.transforms.BlackBoxNotFoundException: BlackBox '/blackboxes/IDontExist.v' not found. Did you misspell it? Is it in src/{main,test}/resources?
[info]   at firrtl.transforms.BlackBoxSourceHelper.firrtl$transforms$BlackBoxSourceHelper$$safeFile(BlackBoxSourceHelper.scala:80)
[info]   at firrtl.transforms.BlackBoxSourceHelper$$anonfun$1.applyOrElse(BlackBoxSourceHelper.scala:95)
[info]   at firrtl.transforms.BlackBoxSourceHelper$$anonfun$1.applyOrElse(BlackBoxSourceHelper.scala:93)
[info]   at scala.PartialFunction.$anonfun$runWith$1$adapted(PartialFunction.scala:141)
[info]   at scala.collection.Iterator.foreach(Iterator.scala:929)
[info]   at scala.collection.Iterator.foreach$(Iterator.scala:929)
[info]   at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
[info]   at scala.collection.IterableLike.foreach(IterableLike.scala:71)
[info]   at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
[info]   at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[info]   ...
[info]   Cause: java.io.FileNotFoundException: /blackboxes/IDontExist.v (No such file or directory)
[info]   at firrtl.transforms.BlackBoxSourceHelper$.copyResourceToFile(BlackBoxSourceHelper.scala:144)
[info]   at firrtl.transforms.BlackBoxSourceHelper$.writeResourceToDirectory(BlackBoxSourceHelper.scala:132)
[info]   at firrtl.transforms.BlackBoxSourceHelper$$anonfun$1.$anonfun$applyOrElse$1(BlackBoxSourceHelper.scala:95)
[info]   at firrtl.transforms.BlackBoxSourceHelper.firrtl$transforms$BlackBoxSourceHelper$$safeFile(BlackBoxSourceHelper.scala:79)
[info]   at firrtl.transforms.BlackBoxSourceHelper$$anonfun$1.applyOrElse(BlackBoxSourceHelper.scala:95)
[info]   at firrtl.transforms.BlackBoxSourceHelper$$anonfun$1.applyOrElse(BlackBoxSourceHelper.scala:93)
[info]   at scala.PartialFunction.$anonfun$runWith$1$adapted(PartialFunction.scala:141)
[info]   at scala.collection.Iterator.foreach(Iterator.scala:929)
[info]   at scala.collection.Iterator.foreach$(Iterator.scala:929)
[info]   at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
[info]   ...
```

### CODE REVIEW

File: src/test/scala/firrtlTests/transforms/BlacklBoxSourceHelperSpec.scala [hunk 1]
```diff
@@ -105,5 +105,21 @@ class BlacklBoxSourceHelperTransformSpec extends LowTransformSpec {
...
   }
-}
 
+  behavior of "BlackBox resources that do not exist"
+
+  it should "provide a useful error message for BlackBoxResourceAnno" in {
+    val annos = Seq( BlackBoxTargetDirAnno("test_run_dir"),
+                     BlackBoxResourceAnno(moduleName, "/blackboxes/IDontExist.v") )
+    (the [BlackBoxNotFoundException] thrownBy {
+       execute(input, "", annos) } getMessage) should include ("Did you misspell it?")
```
Comment (jackkoenig) [inline src/test/scala/firrtlTests/transforms/BlacklBoxSourceHelperSpec.scala]: Generally Postfix notation should not be used, I think it's a warning.
```suggestion
       execute(input, "", annos) }).getMessage should include ("Did you misspell it?")
```

File: src/test/scala/firrtlTests/transforms/BlacklBoxSourceHelperSpec.scala [hunk 2]
```diff
@@ -105,5 +105,21 @@ class BlacklBoxSourceHelperTransformSpec extends LowTransformSpec {
...
+  }
+
+  it should "provide a useful error message for BlackBoxPathAnno" in {
+    val absPath = new java.io.File("src/test/resources/blackboxes/IDontExist.v").getCanonicalPath
+    val annos = Seq( BlackBoxTargetDirAnno("test_run_dir"),
+                     BlackBoxPathAnno(moduleName, absPath) )
+    (the [BlackBoxNotFoundException] thrownBy {
+       execute(input, "", annos) } getMessage) should include ("Did you misspell it?")
```
Comment (jackkoenig) [inline src/test/scala/firrtlTests/transforms/BlacklBoxSourceHelperSpec.scala]: Generally Postfix notation should not be used, I think it's a warning.
```suggestion
       execute(input, "", annos) }).getMessage should include ("Did you misspell it?")
```

File: src/main/scala/firrtl/transforms/BlackBoxSourceHelper.scala [hunk 3]
```diff
@@ -126,7 +142,7 @@ object BlackBoxSourceHelper {
   def copyResourceToFile(name: String, file: File) {
     val in = getClass.getResourceAsStream(name)
     if (in == null) {
-      throw new FileNotFoundException(s"Resource '$name'")
+      throw new FileNotFoundException(s"$name (No such file or directory)")
```
Comment (jackkoenig) [inline src/main/scala/firrtl/transforms/BlackBoxSourceHelper.scala]: Why not wrap this in `safeFile` or otherwise throw a `BlackBoxNotFoundException`?

Comment (seldridge) [reply src/main/scala/firrtl/transforms/BlackBoxSourceHelper.scala]: I'm trying to provide equivalence with how `new FileInputStream(...)` behaves in terms of exceptions thrown so all the `safeFile` wrappers are one level up. Does that make sense?

I could extend `safeFile` to also catch `NullPointerException` and then wrap the file write code in this. However, that seems overly broad. What do you think?

Comment (seldridge) [reply src/main/scala/firrtl/transforms/BlackBoxSourceHelper.scala]: Actually, that isn't overly broad as `safeFile` is private... It should be fine to catch the `NullPointerException`. That makes things cleaner. Good suggestion.

File: src/test/scala/firrtlTests/transforms/BlacklBoxSourceHelperSpec.scala (hunk 1 above)
Comment (seldridge) [reply src/test/scala/firrtlTests/transforms/BlacklBoxSourceHelperSpec.scala]: Fixed in the fixup commit.

File: src/test/scala/firrtlTests/transforms/BlacklBoxSourceHelperSpec.scala (hunk 2 above)
Comment (seldridge) [reply src/test/scala/firrtlTests/transforms/BlacklBoxSourceHelperSpec.scala]: Fixed in the fixup commit.

File: src/main/scala/firrtl/transforms/BlackBoxSourceHelper.scala (hunk 3 above)
Comment (seldridge) [reply src/main/scala/firrtl/transforms/BlackBoxSourceHelper.scala]: Fixed in the fixup commit. Catching the `NullPointerException` does mean that the full stack trace won't give you the `FileNotFoundException` below the `BlackBoxNotFoundException`, but I don't think that's a big deal. The top-level exception should be the one that matters and that contains the correct information.

File: src/main/scala/firrtl/transforms/BlackBoxSourceHelper.scala [hunk 4]
```diff
@@ -35,6 +35,13 @@ case class BlackBoxPathAnno(target: ModuleName, path: String) extends BlackBoxHe
   override def serialize: String = s"path\n$path"
 }
 
+/** Exception indicating that a blackbox wasn't found
+  * @param fileName the name of the BlackBox file (only used for error message generation)
+  * @param e an underlying exception that generated this
+  */
+class BlackBoxNotFoundException(fileName: String, e: Throwable = null) extends FIRRTLException(
+  s"BlackBox '$fileName' not found. Did you misspell it? Is it in src/{main,test}/resources?", e)
```
[the remark this answers is not in the document]
Comment (seldridge) [reply src/main/scala/firrtl/transforms/BlackBoxSourceHelper.scala]: I may be biased in thinking that a user is doing test driven development. If you're running tests, e.g., in Chisel3, then anything in `src/test/resources` is okay and is fair game for being picked up. If you're not running tests, then I don't think this will get picked up. Do you think that this is confusing and should be removed?

Concretely, the following Chisel tests pass where `foo.v` is in src/test/resources, `bar.v` is in src/main/resources, and `baz.v` does not exist:
```scala
package chiselTests

import chisel3._
import chisel3.util.HasBlackBoxResource
import chisel3.experimental.MultiIOModule
import firrtl.transforms.BlackBoxNotFoundException

class Top(resource: String) extends MultiIOModule {
  val bb = Module(new BB(resource))
}

class BB(resource: String) extends BlackBox with HasBlackBoxResource {
  val io = IO(new Bundle {})
  setResource(resource)
}

class Sandbox extends ChiselFlatSpec {
  behavior of "Blackbox"

  it should "work since foo.v is in src/test/resources" in {
    Driver.execute(Array("-X", "verilog"), () => new Top("/foo.v"))
  }

  it should "work since bar.v is in src/main/resources" in {
    Driver.execute(Array("-X", "verilog"), () => new Top("/bar.v"))
  }

  it should "provide a good error message since baz.v doesn't exist" in {
    (the [BlackBoxNotFoundException] thrownBy { Driver.execute(Array("-X", "verilog"), () => new Top("/baz.v")) })
      .getMessage should include ("Is it in src/{main,test}/resources?")
  }
}
```

Then running this:
```
> find src -name \*.v && sbt "testOnly chiselTests.Sandbox"
src/main/resources/bar.v
src/test/resources/chisel3/VerilogVendingMachine.v
src/test/resources/chisel3/BlackBoxTest.v
src/test/resources/chisel3/AnalogBlackBox.v
src/test/resources/foo.v
[info] ...
[info] [0.000] Elaborating design...
[info] [0.004] Done elaborating.
[info] Sandbox:
[info] Blackbox
[info] - should work since foo.v is in src/test/resources
[info] - should work since bar.v is in src/main/resources
[info] - should provide a good error message since baz.v doesn't exist
[info] ScalaTest
[info] Run completed in 3 seconds, 584 milliseconds.
[info] Total number of tests run: 3
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 3, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[info] Passed: Total 3, Failed 0, Errors 0, Passed 3
[success] Total time: 42 s, completed Oct 24, 2018 6:52:33 PM
```

[the remark this answers is not in the document]
Comment (jackkoenig) [reply src/main/scala/firrtl/transforms/BlackBoxSourceHelper.scala]: That's fair, yeah I was thinking more for people using chisel/firrtl in rocket-chip, but in general we encourage people to use ScalaTest for testing. I think you have the right error message.
