### PR TITLE
Don't const-prop a register's self-init

### LINKED ISSUE #1214: Firrtl raises java.lang.AssertionError only when --no-dce option is added
**Type of issue**: bug report

**What is the current behavior?**
I'm from chisel-users mailing list and I was encouraged to post this issue(that mail is [here](https://groups.google.com/forum/#!topic/chisel-users/JIq91Ke3TnU)).

If I use `--no-dce` option, firrtl raises `java.lang.AssertionError` exception when trying below sample code to elaborate(stacktrace is in Other Information).
```
circuit Stage :
  module Stage :
    input CLK : Clock
    input RST : UInt<1>
  
    reg stage0 : { active : UInt<1>, params : { arg : UInt<8>}}, CLK with :
      reset => (UInt<1>("h0"), stage0)      
    stage0 is invalid
      
    when stage0.active :
      skip

    when RST :
      stage0.active <= UInt<1>("h0")
    else :
      when stage0.active :
        stage0.active <= UInt<1>("h0")
```
And fixed version works correctly (at least, there is no exception).
```
circuit Stage :
  module Stage :
    input CLK : Clock
    input RST : UInt<1>

    wire TMP_0: { active : UInt<1>, params : { arg : UInt<8>}}
    TMP_0 is invalid
    TMP_0.active <= UInt<8>(0)
    
    reg stage0 : { active : UInt<1>, params : { arg : UInt<8>}}, CLK with :
      reset => (RST, TMP_0)

    when stage0.active :
      skip

    when stage0.active :
      stage0.active <= UInt<1>("h0")
```
To be honest, I don't know whether this is a bug or not. 
This may be expected behavior.
However, I feel weird that it happens only when `--no-dce` option is added.

**What is the expected behavior?**
I want firrtl to cause error regardless there is `--no-dce` or not.
And also, If could, showing only error message instead of exception with stack trace.

**Please tell us about your environment:**
    - version: `1.2.0`
    - OS: `Linux soya 5.0.0-32-generic #34~18.04.2-Ubuntu SMP Thu Oct 10 10:36:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

**Impact**: unknown

**Other information** 
stack trace is here.

```
Exception in thread "main" java.lang.AssertionError: assertion failed: Error! Synchronous reset should have been removed!
	at scala.Predef$.assert(Predef.scala:223)
	at firrtl.VerilogEmitter$VerilogRender.regUpdate(Emitter.scala:568)
	at firrtl.VerilogEmitter$VerilogRender.build_streams(Emitter.scala:724)
	at firrtl.VerilogEmitter$VerilogRender.$anonfun$build_streams$1(Emitter.scala:715)
	at firrtl.VerilogEmitter$VerilogRender.$anonfun$build_streams$1$adapted(Emitter.scala:715)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at firrtl.ir.Block.foreachStmt(IR.scala:375)
	at firrtl.traversals.Foreachers$StmtForMagnet$$anon$1.foreach(Foreachers.scala:18)
	at firrtl.traversals.Foreachers$StmtForeach$.foreach$extension(Foreachers.scala:35)
	at firrtl.VerilogEmitter$VerilogRender.build_streams(Emitter.scala:715)
	at firrtl.VerilogEmitter$VerilogRender.$anonfun$build_streams$1(Emitter.scala:715)
	at firrtl.VerilogEmitter$VerilogRender.$anonfun$build_streams$1$adapted(Emitter.scala:715)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at firrtl.ir.Block.foreachStmt(IR.scala:375)
	at firrtl.traversals.Foreachers$StmtForMagnet$$anon$1.foreach(Foreachers.scala:18)
	at firrtl.traversals.Foreachers$StmtForeach$.foreach$extension(Foreachers.scala:35)
	at firrtl.VerilogEmitter$VerilogRender.build_streams(Emitter.scala:715)
	at firrtl.VerilogEmitter$VerilogRender.$anonfun$build_streams$1(Emitter.scala:715)
	at firrtl.VerilogEmitter$VerilogRender.$anonfun$build_streams$1$adapted(Emitter.scala:715)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at firrtl.ir.Block.foreachStmt(IR.scala:375)
	at firrtl.traversals.Foreachers$StmtForMagnet$$anon$1.foreach(Foreachers.scala:18)
	at firrtl.traversals.Foreachers$StmtForeach$.foreach$extension(Foreachers.scala:35)
	at firrtl.VerilogEmitter$VerilogRender.build_streams(Emitter.scala:715)
	at firrtl.VerilogEmitter$VerilogRender.emit_verilog(Emitter.scala:922)
	at firrtl.VerilogEmitter.$anonfun$emit$3(Emitter.scala:974)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at firrtl.VerilogEmitter.emit(Emitter.scala:968)
	at firrtl.VerilogEmitter.$anonfun$execute$3(Emitter.scala:983)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:245)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:245)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:242)
	at scala.collection.immutable.List.flatMap(List.scala:355)
	at firrtl.VerilogEmitter.execute(Emitter.scala:980)
	at firrtl.Transform.$anonfun$runTransform$2(Compiler.scala:216)
	at firrtl.Utils$.time(Utils.scala:169)
	at firrtl.Transform.runTransform(Compiler.scala:216)
	at firrtl.Compiler.$anonfun$compile$2(Compiler.scala:480)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
	at scala.collection.immutable.List.foldLeft(List.scala:89)
	at firrtl.Compiler.$anonfun$compile$1(Compiler.scala:478)
	at firrtl.Utils$.time(Utils.scala:169)
	at firrtl.Compiler.compile(Compiler.scala:478)
	at firrtl.Compiler.compile$(Compiler.scala:474)
	at firrtl.VerilogCompiler.compile(LoweringCompilers.scala:164)
	at firrtl.stage.phases.Compiler.f$1(Compiler.scala:91)
	at firrtl.stage.phases.Compiler.$anonfun$internalTransform$2(Compiler.scala:95)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at firrtl.stage.phases.Compiler.internalTransform(Compiler.scala:95)
	at firrtl.stage.phases.Compiler.internalTransform(Compiler.scala:45)
	at firrtl.options.Translator.transform(Phase.scala:140)
	at firrtl.options.Translator.transform$(Phase.scala:140)
	at firrtl.stage.phases.Compiler.transform(Compiler.scala:45)
	at firrtl.options.phases.DeletedWrapper.internalTransform(DeletedWrapper.scala:32)
	at firrtl.options.phases.DeletedWrapper.internalTransform(DeletedWrapper.scala:15)
	at firrtl.options.Translator.transform(Phase.scala:140)
	at firrtl.options.Translator.transform$(Phase.scala:140)
	at firrtl.options.phases.DeletedWrapper.transform(DeletedWrapper.scala:15)
	at firrtl.stage.FirrtlStage.$anonfun$run$1(FirrtlStage.scala:28)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
	at scala.collection.immutable.List.foldLeft(List.scala:89)
	at firrtl.stage.FirrtlStage.run(FirrtlStage.scala:28)
	at firrtl.options.Stage$$anon$1.transform(Stage.scala:43)
	at firrtl.options.Stage$$anon$1.transform(Stage.scala:43)
	at firrtl.options.phases.DeletedWrapper.internalTransform(DeletedWrapper.scala:32)
	at firrtl.options.phases.DeletedWrapper.internalTransform(DeletedWrapper.scala:15)
	at firrtl.options.Translator.transform(Phase.scala:140)
	at firrtl.options.Translator.transform$(Phase.scala:140)
	at firrtl.options.phases.DeletedWrapper.transform(DeletedWrapper.scala:15)
	at firrtl.options.Stage.$anonfun$transform$5(Stage.scala:46)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
	at scala.collection.immutable.List.foldLeft(List.scala:89)
	at firrtl.options.Stage.$anonfun$transform$3(Stage.scala:46)
	at logger.Logger$.$anonfun$makeScope$2(Logger.scala:168)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at logger.Logger$.makeScope(Logger.scala:166)
	at firrtl.options.Stage.transform(Stage.scala:46)
	at firrtl.options.Stage.execute(Stage.scala:57)
	at firrtl.options.StageMain.main(Stage.scala:70)
	at firrtl.stage.FirrtlMain.main(FirrtlStage.scala)
```

### PR DESCRIPTION
**Pull request by albert-magyar**
* Avoids passing un-emittable code to emitter under no-DCE
* Fixes #1214

Currently, the aggressive inlining of expressions in `ConstantPropagation` gets rid of *all* `WRef`s to constant signals. However, this generates odd (and emitter-unfriendly) code when it tramples on the register's self-reset. Normally, this gets masked by the DCE of the constant register, but the ``--no-dce`` flag keeps it around, which leads to assertion failures in the emitter.

I added a test case that is a smaller example than the one from #1214.

**Type of improvement:** bugfix
**API impact:** none
**Backend code-generation impact:** none
**Desired merge strategy:** squash

### Contributor Checklist

- [ ] Did you add Scaladoc to every public function/method?
- [ ] Did you add at least one test demonstrating the PR?
- [ ] Did you delete any extraneous printlns/debugging code?
- [ ] Did you specify the type of improvement?
- [ ] Did you state the API impact?
- [ ] Did you specify the code generation impact?
- [ ] Did you request a desired merge strategy?

### Reviewer Checklist (only modified by reviewer)
- [ ] Did you add the appropriate labels?
- [ ] Did you mark the proper milestone (1.2.x, 1.3.0, 1.4.0) ?
- [ ] Did you review?
- [ ] Did you mark as `Please Merge`?

### CODE REVIEW

File: src/main/scala/firrtl/transforms/ConstantPropagation.scala [hunk 1]
```diff
@@ -481,17 +481,23 @@ class ConstantPropagation extends Transform with ResolvedAnnotationPaths {
...
-          case wire: DefWire => wire.copy(name = newName)
-          case reg: DefRegister => reg.copy(name = newName)
-          case other => throwInternalError()
-        }
-      case other => other map backPropStmt
+    def backPropStmt(stmt: Statement): Statement = stmt match {
+      case reg: DefRegister if (WrappedExpression.weq(reg.init, WRef(reg))) =>
+        // Self-init reset is an idiom for "no reset," and must be handled separately
+        val updatedName = swapMap.getOrElse(reg.name, reg.name)
+        reg.copy(name = updatedName, init = WRef(reg).copy(name = updatedName))
```
Comment (jackkoenig) [inline src/main/scala/firrtl/transforms/ConstantPropagation.scala]: I'm assuming it's intentional that you're not calling `map backPropExpr` on registers with self-init. Could you elaborate on why that is?

Comment (albert-magyar) [reply src/main/scala/firrtl/transforms/ConstantPropagation.scala]: Avoiding transforming the `init` field when it is a self-reference is basically the contribution of this PR. Otherwise, `ConstantPropagation` will transform something like this:
`reg r: UInt<1>, clk with: (reset => (rst, r))`

Into something like this for the case where `r` is constant zero:
`reg r: UInt<1>, clk with: (reset => (rst, UInt<1>(0)))`

Not calling `map backPropExpr` in those cases is the least invasive way to fix that problem.

The fact that it avoids calling `map backPropExpr` also impacts the other two expression fields: `clock` and `reset`. Since a self-reset register is already analyzed as having "no reset," and since there is a dependency on `RemoveReset` for register const prop to work at all, there is no benefit to calling `backPropExpr` on the `reset` expression, though I suppose it couldn't hurt. I sincerely hope that we aren't const-propping `clock` :)

Comment (jackkoenig) [reply src/main/scala/firrtl/transforms/ConstantPropagation.scala]: Got it, thanks for the explanation

Comment (jackkoenig) [inline src/main/scala/firrtl/transforms/ConstantPropagation.scala]:
```suggestion
        swapMap.get(reg.name)
               .map(newName => reg.copy(name = newName, init = WRef(reg).copy(name = newName)))
               .getOrElse(reg)
```
I'm not sure if it's worth trying to optimize these object allocations since every `map whatever` is returning a new object even if it doesn't change anything, but we could.

Comment (albert-magyar) [reply src/main/scala/firrtl/transforms/ConstantPropagation.scala]: Whenever I "peephole fix" code I try to more or less make new cases blindly resemble the style of the existing cases, but this is your code and I am generally a fan of relying on `None.map` for the common case of non-const-propped registers :)
