### PR TITLE
Give better error when mport references non-existant memory.

### LINKED ISSUE #796: mports without a declared mem hard errors
* **Type of issue**
  - [x ] Bug report

* **If the current behavior is a bug, please provide the steps to reproduce the problem:**
  * **If possible, please directly provide the FIRRTL file or a relevant fragment if the file is large**
```
circuit testTestModule :
  module testTestModule :
    input clock : Clock
    input reset : UInt<1>
    output io : {flip in : UInt<10>, out : UInt<10>}

    node _T_10 = bits(io.in, 1, 0)
    read mport _T_11 = m[_T_10], clock
    io.out <= _T_11
```
  * **What is the current behavior?**
Hard error, says to file an issue
  * **What is the expected behavior?**
It should say that m is not declared as a memory.

  * **Please tell us about your environment:**
    (examples)
    - version: `1.1.0`
    - OS: `OS X 10.13.4`

* **What is the use case for changing the behavior?**
See [the related Chisel issue](https://github.com/freechipsproject/chisel3/issues/815) for more information. In short, `new Mem()` (as opposed to `Mem()`) gives an inscrutable error message.

* **Impact**
  - [ x ] API addition (no impact on existing code)

* **Development Phase**
  - [ x ] request

### PR DESCRIPTION
**Pull request by grebe**
Closes #796.

### CODE REVIEW

File: src/test/scala/firrtlTests/ChirrtlMemSpec.scala [hunk 1]
```diff
@@ -108,6 +108,23 @@ circuit foo :
...
+         |  module testTestModule :
+         |    input clock : Clock
+         |    input reset : UInt<1>
+         |    output io : {flip in : UInt<10>, out : UInt<10>}
+         |
+         |    node _T_10 = bits(io.in, 1, 0)
+         |    read mport _T_11 = m[_T_10], clock
+         |    io.out <= _T_11""".stripMargin
+    assertThrows[PassException] {
+      (new LowFirrtlCompiler).compile(CircuitState(parse(input), ChirrtlForm), Seq()).circuit
```
Comment (seldridge) [inline src/test/scala/firrtlTests/ChirrtlMemSpec.scala]: Can you check the message thrown? This introduces some brittleness on the exception message, but I think that's warranted versus aliasing of this to any `PassException`.

I think the following does it:
```scala
intercept[PassException]{ (new LowFirrtlCompiler).compile(CircuitState(parse(input), ChirrtlForm), Seq()).circuit }
  .getMessage should startWith ("Undefined memory m referenced by mport _T_11") // I think I have this right?
```

Comment (grebe) [reply src/test/scala/firrtlTests/ChirrtlMemSpec.scala]: I didn't know you could do that! Good thought

**Comment by seldridge** [comment]
And Traivs :fist_left: not finding Verilator now...
