### PR TITLE
Remove DiGraph.seededLinearize

### LINKED ISSUE #1247: Remove DiGraph.seededLinearize
tl;dr: My `DiGraph.seededLinearize` method doesn't make any sense and should probably be removed.

I'm filing this as a tracking issue in case anybody tries to use this method.

### Checklist

- [x] Did you specify the current behavior?
- [x] Did you specify the expected behavior?
- [x] Did you provide a code example showing the problem?
- [x] Did you describe your environment?
- [x] Did you specify relevant external information?

### What is the current behavior?

`DiGraph.seededLinearize` was a method I added to try and tease out one possible linearization from the space of all possible linearizations. I did this by adding a "seed" which would be used to see the initial DFS. However, seeding a DFS doesn't matter as nodes are being walked **in the order in which the edges are stored**. So, this method doesn't really have a point except it works for all test cases currently explored in the dependency API.

### What is the expected behavior?

The expected behavior is that this would result in a specific order in which nodes are walked. This can be done inside the `seededLinearize` method or with an implicit ordering. However, it likely makes more sense to just remove this method.

If a user that wants a specific ordering can instead, produce a new `DiGraph` with everything in the order they want, e.g., [the approach taken in the Dependency API PR](https://github.com/freechipsproject/firrtl/pull/1123/commits/da7c4293e25281b0eaf837c64f4467f956b52d10#diff-4aa6423289d5fcb0bcd5aee390090c4bR206).

### Steps to Reproduce

(Intentionally poorly documented steps to reproduce because I'm not intending somebody to jump in and fix this. I'm only expecting for this method to be removed in 1.3.0.)

Running the following test case with the old logic will fail: 
 
 - https://github.com/freechipsproject/firrtl/pull/1123/commits/9b9ef2826e0a6b86835620333c93f39dd7c8f966

### Your environment

- `dependency-api-2` branch: 9b9ef2826e0a6b86835620333c93f39dd7c8f966 (this commit will probably disappear due to a rebase)

### External Information

None.

### PR DESCRIPTION
**Pull request by seldridge**
This removes the `seededLinearize` method added in #1079.

The original motivation here was to be able to seed the order in which vertices in a graph were explored during topological sorting. However, this method is really just providing an ordering for the _initial_ set of BFS vertices. This isn't enough as you really want to explore all vertices _and their edges_ in a specific order. The better way to do this is to sort the edges the way you want and then pass this into the existing topological sort method, `linearize`. ([This is how it works in the current version of the `DependencyManager`](https://github.com/freechipsproject/firrtl/blob/master/src/main/scala/firrtl/options/DependencyManager.scala#L192).)

Fixes #1247.

### Contributor Checklist

- [x] Did you add Scaladoc to every public function/method?
- [x] Did you add at least one test demonstrating the PR?
- [x] Did you delete any extraneous printlns/debugging code?
- [x] Did you specify the type of improvement?
- [x] Did you state the API impact?
- [x] Did you specify the code generation impact?
- [x] Did you request a desired merge strategy?

### Type of Improvement

- API Removal

### API Impact

This removes the `DiGraph.seededLinearize` method.

### Backend Code Generation Impact

None.

### Desired Merge Strategy

- Squash: The PR will be squashed and merged (choose this if you have no preference.

### Reviewer Checklist (only modified by reviewer)
- [ ] Did you add the appropriate labels?
- [ ] Did you mark the proper milestone (1.2.x, 1.3.0, 1.4.0) ?
- [ ] Did you review?
- [ ] Did you mark as `Please Merge`?

### CODE REVIEW

File: src/main/scala/firrtl/graph/DiGraph.scala [hunk 1]
```diff
@@ -81,7 +104,7 @@ class DiGraph[T] private[graph] (private[graph] val edges: LinkedHashMap[T, Link
     case class LinearizeFrame[A](v: A, expanded: Boolean)
     val callStack = mutable.Stack[LinearizeFrame[T]]()
 
-    unmarked ++= seed.getOrElse(getVertices)
+    unmarked ++= getVertices
```
Comment (albert-magyar) [inline src/main/scala/firrtl/graph/DiGraph.scala]: Looks good now.

**Comment by seldridge** [comment]
Yeah, the diff algorithm can't handle what's going on... (I was trying to clean this up in a rebase, but forgot to actually remove the use of the `seed`... Fixing in a rebase.)
