### PR TITLE
Make CheckCombLoops find combinational nodes with self-edges

### LINKED ISSUE #836: Combinational Loop not detected for self-connections
**Type of issue**: bug report

 * **What is the current behavior?**
firrtl input:
```
circuit loop :
  module loop :
    output y : UInt<8>

    wire w : UInt<8>
    w <= w
    y <= w
```
emitted verilog:
```
module loop( // @[:combLoop.fir@2.2]
  output [7:0] y // @[:combLoop.fir@3.4]
);
  wire [7:0] w; // @[:combLoop.fir@5.4]
  assign y = w; // @[:combLoop.fir@7.4]
  assign w = w; // @[:combLoop.fir@6.4]
endmodule
```

  * **What is the expected behavior?**
throw `CombLoopException`

**Impact**: no functional change

**Development Phase**: request

### PR DESCRIPTION
**Pull request by albert-magyar**
Fixes #836

### CODE REVIEW

File: src/main/scala/firrtl/transforms/CheckCombLoops.scala [hunk 1]
```diff
@@ -199,8 +199,12 @@ class CheckCombLoops extends Transform {
       val moduleGraph = DiGraph(internalDeps)
       moduleGraphs(m.name) = moduleGraph
       simplifiedModuleGraphs(m.name) = moduleGraphs(m.name).simplify((m.ports map { p => LogicNode(p.name) }).toSet)
-      for (scc <- moduleGraphs(m.name).findSCCs.filter(_.length > 1)) {
-        val sccSubgraph = moduleGraphs(m.name).subgraph(scc.toSet)
+      // Find combinational nodes with self-edges; this is *NOT* the same as length-1 SCCs!
+      for (unitLoopNode <- moduleGraph.getVertices.filter(v => moduleGraph.getEdges(v).contains(v))) {
+        errors.append(new CombLoopException(m.info, m.name, Seq(unitLoopNode.name)))
+      }
```
Comment (jackkoenig) [inline src/main/scala/firrtl/transforms/CheckCombLoops.scala]: Are we sure that Scala or the JVM is going to CSE the inner `moduleGraph.getEdges(v).contains(v)`? If it doesn't this would be very slow.

Comment (albert-magyar) [reply src/main/scala/firrtl/transforms/CheckCombLoops.scala]: Not sure I follow

Comment (jackkoenig) [reply src/main/scala/firrtl/transforms/CheckCombLoops.scala]: Nevermind, I was assuming `.getEdges` iterates on all of the edges like `getVertices` iterates on all of the vertices does but it does not 😇

Comment (albert-magyar) [reply src/main/scala/firrtl/transforms/CheckCombLoops.scala]: Yeah, I was confused, since this is **|V|** times two hash table lookups. It's so much faster than the rest of the pass :)

Comment (jackkoenig) [reply src/main/scala/firrtl/transforms/CheckCombLoops.scala]: Yeah I was worried it was **|V| * |E|**... which I guess would still have been faster than the rest of the pass 🤷‍♀️

Comment (albert-magyar) [reply src/main/scala/firrtl/transforms/CheckCombLoops.scala]: No, the pass runs in **|E|** lol

Comment (jackkoenig) [reply src/main/scala/firrtl/transforms/CheckCombLoops.scala]: Oh word 💯
